### ISSUE TITLE
Duplicate typedefs in types.h

### ISSUE THREAD

**Issue by siliconforks** [libyal/libfdatetime#4]
`libfdatetime_fat_date_time_t` and `libfdatetime_fat_date_t` are defined twice in `types.h`:

https://github.com/libyal/libfdatetime/blob/47838cea8a01e7623bf61e37cde7f0f279c5956f/include/libfdatetime/types.h.in#L205-L216

This causes GCC to generate a warning when the `-pedantic` option is used.

**Comment by joachimmetz** [comment]
Thanks for flagging I'll have a look when time permits. Looks like this is not causing any issues for now.

**Comment by siliconforks** [comment]
> Looks like this is not causing any issues for now.

Indeed, I think this is just a compiler warning.  (The code still compiles.)

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libfdatetime/commit/e1af11da0dbbce6b6b4c25842c39d440984c6571
