### ISSUE TITLE
GCC -pedantic warning: ISO C restricts enumerator values to range of ‘int’

### ISSUE THREAD

**Issue by siliconforks** [libyal/libfdatetime#5]
The `enum` value `LIBFDATETIME_STRING_FORMAT_FLAG_TIMEZONE_INDICATOR` is defined as `0x80000000UL` in `definitions.h`:

https://github.com/libyal/libfdatetime/blob/47838cea8a01e7623bf61e37cde7f0f279c5956f/include/libfdatetime/definitions.h.in#L79

GCC generates a warning for this when the `-pedantic` option is used: `ISO C restricts enumerator values to range of ‘int’`.

Is it possible to change this to a different value?  (Or perhaps it should not be an `enum` at all?)

**Comment by joachimmetz** [comment]
Is causing an actual issue or is it just a compiler warning?

**Comment by siliconforks** [comment]
I think this is just a compiler warning.

**Comment by joachimmetz** [comment]
Closing given this appears mostly to be a cosmetic issue.
